# PinGuard Configuration File
# Scan settings
scanner:
  modules:
    package_audit: true
    kernel_check: true
    permission_audit: true
    service_audit: true
    user_audit: true
    network_audit: true
  concurrent_scans: true
  max_scan_time: 300  # seconds
  
# Report settings
report:
  format: "json"
  output_dir: "./reports"
  template: "default"

# Database settings
database:
  path: "./pinGuard.db"
  auto_migrate: true
  connection_pool_size: 10
  
# CVE database settings  
cve:
  api_url: "https://services.nvd.nist.gov/rest/json/cves/2.0"
  cache_duration: 86400  # 24 hours (seconds)
  auto_update: true

# Fixer settings
fixer:
  auto_fix: false
  require_confirmation: true
  backup_before_fix: true
  backup_dir: "./backups"
  enabled_modules:
    - "package_updater"
    - "kernel_updater"
    - "permission_fixer"
    - "service_hardener"
    - "user_policy_fixer"
    - "firewall_configurator"
